version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:21.0.6'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=hoangtien2k3_reactify

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud