server:
  port: 8899
logging:
  pattern:
    console: "%d{dd/MM/yy HH:mm:ss}|%X{traceId}|%m%n"
  level:
    root: INFO
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

# spring config
spring:
  application:
    name: auth-service
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/messages

# web client config
client:
  base-currency:
    address: http://www.geoplugin.net
    name: baseCurrencyClient

# minio server config
minio:
  bucket: ezbuy-bucket
  enabled: true
  baseUrl: http://localhost:9000
  publicUrl: http://localhost:9000
  accessKey: q875aHMpdL6IJ3n9ruil
  secretKey: Q43tehRDv55Sw67ktA0pQdztEbtQjvinLOk6zwB3
  private:
    bucket: ezbuy-private

