server:
  port: 8899
logging:
  pattern:
    console: "%d{dd/MM/yy HH:mm:ss}|%X{traceId}|%m%n"
  level:
    root: INFO
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

# spring config
spring:
  application:
    name: auth-service
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/messages

  security:
    oauth2:
      client:
        provider:
          oidc:
            token-uri: ${keycloak.serverUrl}/realms/${keycloak.realm}/protocol/openid-connect/token
        registration:
          oidc:
            client-id: ${keycloak.clientId}
            client-secret: ${keycloak.clientSecret}
            authorization-grant-type: ${keycloak.grantType} #password || #client_credentials
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.serverUrl}/realms/${keycloak.realm}/protocol/openid-connect/certs
      keycloak:
        client-id: ${keycloak.clientId}

# web client config
client:
  #keycloak
  keycloak:
    address: http://localhost:8080/realms/ezbuy-server/protocol/openid-connect
    name: keycloak
    auth:
      client-id: ezbuy-client
      client-secret: mI92QDfvi20tZgFtjpRAPWu8TR6eMHmw
  base-currency:
    address: http://www.geoplugin.net
    name: baseCurrencyClient

#keycloak client config
keycloak:
  clientId: ezbuy-client
  clientSecret: mI92QDfvi20tZgFtjpRAPWu8TR6eMHmw
  realm: ezbuy-server
  serverUrl: http://localhost:8080
  grantType: password
  host: localhost

# minio server config
minio:
  bucket: ezbuy-bucket
  enabled: true
  baseUrl: http://localhost:9000
  publicUrl: http://localhost:9000
  accessKey: q875aHMpdL6IJ3n9ruil
  secretKey: Q43tehRDv55Sw67ktA0pQdztEbtQjvinLOk6zwB3
  private:
    bucket: ezbuy-private


# unauthenticated endpoints config
application:
  http-logging:
    request:
      enable: true
      header: true
      param: true
      body: true
    response:
      enable: true
      body: true
  whiteList:
    - uri: /login
      methods:
        - POST
    - uri: /students
      methods:
        - GET
    - uri: /base-currency
      methods:
        - GET
    - uri: /base-currency?baseCurrency=VN
      methods:
        - GET
    - uri: /clear-by-name
      methods:
        - POST
    - uri: /clear-all
      methods:
        - POST
    - uri: /get-list-cache
      methods:
        - GET
    - uri: /get-token
      methods:
        - GET
    - uri: /token-user
      methods:
        - GET
